#!/usr/bin/env bash
set -euo pipefail

# Purpose: Install Docker CLI (if absent) and configure Docker context in WSL
#          from build artifacts generated by 01-build-cluster/08-access-artifacts.sh.
# Preconditions: Ubuntu-like WSL distro with apt; artifact file docker-host-uri exists.
# Invariants: Artifact-driven only. Does not install/modify Docker daemon on controller VM.
# Idempotency: Safe to rerun; context is reconciled each run.
# Postconditions: Docker CLI installed, context configured and active against artifact endpoint.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ARTIFACT_DIR="${ARTIFACT_DIR:-${SCRIPT_DIR}/../01-build-cluster/artifacts}"
DOCKER_HOST_ARTIFACT="${DOCKER_HOST_ARTIFACT:-${ARTIFACT_DIR}/docker-host-uri}"
WSL_ENV_ARTIFACT="${WSL_ENV_ARTIFACT:-${ARTIFACT_DIR}/wsl.env}"

CONTEXT_NAME="${DOCKER_CONTEXT_NAME:-kubernetes}"
VM_USER="${SUDO_USER:-${USER}}"

# When invoked via sudo, run commands as the original user so their ~/.ssh, agent,
# and DOCKER_CONFIG are available rather than root's.
as_user() {
  if [[ -n "${SUDO_USER:-}" ]]; then
    sudo -u "${VM_USER}" "$@"
  else
    "$@"
  fi
}

log()  { printf '\n[%s] [INFO]  %s\n' "$(date +%H:%M:%S)" "$*"; }
fail() { printf '\n[%s] [ERROR] %s\n' "$(date +%H:%M:%S)" "$*" >&2; exit 1; }

if [[ -f "${WSL_ENV_ARTIFACT}" ]]; then
  # shellcheck disable=SC1090
  source "${WSL_ENV_ARTIFACT}"
  CONTEXT_NAME="${DOCKER_CONTEXT_NAME:-${CONTEXT_NAME}}"
fi

[[ -f "${DOCKER_HOST_ARTIFACT}" ]] \
  || fail "Missing artifact '${DOCKER_HOST_ARTIFACT}'. Run ../01-build-cluster/08-access-artifacts.sh first."

DOCKER_HOST="$(<"${DOCKER_HOST_ARTIFACT}")"
[[ -n "${DOCKER_HOST}" ]] || fail "Artifact '${DOCKER_HOST_ARTIFACT}' is empty"

# ------------------------------------------------------------------------------
# Install Docker CLI if absent
# ------------------------------------------------------------------------------

if ! command -v docker >/dev/null 2>&1; then
  log "Docker CLI not found — installing via official Docker apt repository"

  command -v curl >/dev/null 2>&1 || apt-get install -y curl

  # Add Docker's official GPG key and repository (idempotent)
  apt-get update -y
  apt-get install -y ca-certificates gnupg

  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg

  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu \
$(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" \
    | tee /etc/apt/sources.list.d/docker.list >/dev/null

  apt-get update -y
  # Install the CLI only — no daemon needed in WSL
  apt-get install -y docker-ce-cli docker-buildx-plugin docker-compose-plugin
  log "Docker CLI installed: $(docker --version)"
else
  log "Docker CLI already present: $(docker --version)"
fi

# ------------------------------------------------------------------------------
# Create context
# ------------------------------------------------------------------------------

log "Removing existing Docker context '${CONTEXT_NAME}' if present"
as_user docker context rm "${CONTEXT_NAME}" 2>/dev/null || true

log "Creating Docker context '${CONTEXT_NAME}' -> ${DOCKER_HOST}"
as_user docker context create "${CONTEXT_NAME}" \
  --description "Docker engine endpoint from cluster access artifacts" \
  --docker "host=${DOCKER_HOST}"

# ------------------------------------------------------------------------------
# Activate context
# ------------------------------------------------------------------------------

log "Setting '${CONTEXT_NAME}' as active Docker context"
as_user docker context use "${CONTEXT_NAME}"

# ------------------------------------------------------------------------------
# Verify
# ------------------------------------------------------------------------------

log "Verifying Docker connectivity"
as_user docker info --format 'Server version: {{.ServerVersion}}' \
  || fail "Docker connectivity check failed — review controller reachability and artifact endpoint"

log "Done. Docker context '${CONTEXT_NAME}' is active and verified from artifacts."
