#!/usr/bin/env bash
set -euo pipefail

# Purpose: Install kubectl (if absent) and configure it in WSL using
#          kubeconfig artifacts generated by 01-build-cluster/08-access-artifacts.sh.
# Preconditions: Ubuntu-like WSL distro with apt; kubeconfig artifact exists.
# Invariants: Artifact-driven only. Does not read cluster config remotely over SSH.
# Idempotency: Safe to rerun; context is reconciled each run.
# Postconditions: kubectl installed and context "kubernetes" activated from artifacts.

CONTEXT_NAME="kubernetes"
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ARTIFACT_DIR="${ARTIFACT_DIR:-${SCRIPT_DIR}/../01-build-cluster/artifacts}"
KUBECONFIG_ARTIFACT="${KUBECONFIG_ARTIFACT:-${ARTIFACT_DIR}/kubeconfig-controller-ip.yaml}"
WSL_ENV_ARTIFACT="${WSL_ENV_ARTIFACT:-${ARTIFACT_DIR}/wsl.env}"

VM_USER="${SUDO_USER:-${USER}}"
LOCAL_KUBECONFIG="${HOME}/.kube/config"

# When invoked via sudo, run commands as the original user so their ~/.ssh, agent,
# and KUBECONFIG/home directory are used rather than root's.
as_user() {
  if [[ -n "${SUDO_USER:-}" ]]; then
    sudo -u "${VM_USER}" "$@"
  else
    "$@"
  fi
}

log()  { printf '\n[%s] [INFO]  %s\n' "$(date +%H:%M:%S)" "$*"; }
fail() { printf '\n[%s] [ERROR] %s\n' "$(date +%H:%M:%S)" "$*" >&2; exit 1; }

if [[ -f "${WSL_ENV_ARTIFACT}" ]]; then
  # shellcheck disable=SC1090
  source "${WSL_ENV_ARTIFACT}"
  CONTEXT_NAME="${DOCKER_CONTEXT_NAME:-${CONTEXT_NAME}}"
fi

[[ -f "${KUBECONFIG_ARTIFACT}" ]] \
  || fail "Missing artifact '${KUBECONFIG_ARTIFACT}'. Run ../01-build-cluster/08-access-artifacts.sh first."

TMP_KUBECONFIG="$(mktemp)"
cleanup() { rm -f "${TMP_KUBECONFIG}"; }
trap cleanup EXIT

# ------------------------------------------------------------------------------
# Install kubectl if absent
# ------------------------------------------------------------------------------

if ! command -v kubectl >/dev/null 2>&1; then
  log "kubectl not found — installing via official Kubernetes apt repository"

  command -v curl >/dev/null 2>&1 || apt-get install -y curl

  apt-get update -y
  apt-get install -y apt-transport-https ca-certificates gnupg

  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key \
    | gpg --dearmor --yes -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  chmod a+r /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] \
https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /" \
    | tee /etc/apt/sources.list.d/kubernetes.list >/dev/null

  apt-get update -y
  apt-get install -y kubectl
  log "kubectl installed: $(as_user kubectl version --client --short 2>/dev/null || as_user kubectl version --client)"
else
  log "kubectl already present: $(as_user kubectl version --client --short 2>/dev/null || as_user kubectl version --client)"
fi

# ------------------------------------------------------------------------------
# Stage artifact read
# ------------------------------------------------------------------------------

log "Reading kubeconfig artifact: ${KUBECONFIG_ARTIFACT}"
cp "${KUBECONFIG_ARTIFACT}" "${TMP_KUBECONFIG}"

chmod 600 "${TMP_KUBECONFIG}"

# ------------------------------------------------------------------------------
# Merge into local kubeconfig
# ------------------------------------------------------------------------------

USER_HOME="$(eval echo "~${VM_USER}")"
LOCAL_KUBECONFIG="${USER_HOME}/.kube/config"

log "Ensuring ${LOCAL_KUBECONFIG} exists"
as_user mkdir -p "$(dirname "${LOCAL_KUBECONFIG}")"
as_user touch "${LOCAL_KUBECONFIG}"
chmod 600 "${LOCAL_KUBECONFIG}"

log "Merging into ${LOCAL_KUBECONFIG}"
MERGED="$(mktemp)"
as_user kubectl --kubeconfig="${LOCAL_KUBECONFIG}" config view --flatten \
  --merge "${TMP_KUBECONFIG}" > "${MERGED}"
mv "${MERGED}" "${LOCAL_KUBECONFIG}"
chmod 600 "${LOCAL_KUBECONFIG}"

# ------------------------------------------------------------------------------
# Rename context to a friendly name and activate it
# ------------------------------------------------------------------------------

# The source context name from k0s admin.conf is typically "k0s-admin@k0s" or "admin@k0s";
# rename whatever was imported to CONTEXT_NAME.
IMPORTED_CONTEXT="$(as_user kubectl --kubeconfig="${TMP_KUBECONFIG}" config current-context)"

if [[ "${IMPORTED_CONTEXT}" != "${CONTEXT_NAME}" ]]; then
  log "Renaming context '${IMPORTED_CONTEXT}' -> '${CONTEXT_NAME}'"
  as_user kubectl --kubeconfig="${LOCAL_KUBECONFIG}" config rename-context \
    "${IMPORTED_CONTEXT}" "${CONTEXT_NAME}" 2>/dev/null || true
fi

log "Setting '${CONTEXT_NAME}' as current context"
as_user kubectl --kubeconfig="${LOCAL_KUBECONFIG}" config use-context "${CONTEXT_NAME}"

# ------------------------------------------------------------------------------
# Verify
# ------------------------------------------------------------------------------

log "Verifying API connectivity"
as_user kubectl --kubeconfig="${LOCAL_KUBECONFIG}" cluster-info \
  || fail "kubectl cluster-info failed — check API server reachability and TLS trust."

log "Listing nodes"
as_user kubectl --kubeconfig="${LOCAL_KUBECONFIG}" get nodes -o wide

log "Done. kubectl context '${CONTEXT_NAME}' is active and verified."
