apiVersion: crd.projectcalico.org/v1
kind: IPAMConfig
metadata:
  annotations:
    projectcalico.org/metadata: '{"creationTimestamp":null}'
  creationTimestamp: "2026-03-25T21:28:25Z"
  generation: 2
  name: default
  resourceVersion: "5332"
  uid: bee2dea1-1237-4dde-a5ed-80c77dc129e9
spec:
  autoAllocateBlocks: true
  strictAffinity: true
