apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  annotations:
    projectcalico.org/metadata: '{"creationTimestamp":"2026-03-25T21:28:25Z"}'
  creationTimestamp: "2026-03-25T21:28:25Z"
  generation: 2
  name: default-ipv4-ippool
  resourceVersion: "5318"
  uid: cbefc93a-17b2-4d8e-8bf4-6c0f291a620e
spec:
  allowedUses:
  - Workload
  - Tunnel
  assignmentMode: Automatic
  blockSize: 26
  cidr: 172.16.0.0/16
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Always
