apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s
  namespace: kube-system

spec:
  api:
    address: 192.168.250.10
    port: 6443
    k0sApiPort: 9443
    ca:
      certificatesExpireAfter: 8760h0m0s
      expiresAfter: 87600h0m0s

  controllerManager: {}

  scheduler: {}

  storage:
    type: etcd
    etcd:
      peerAddress: 192.168.250.10
      ca:
        certificatesExpireAfter: 8760h0m0s
        expiresAfter: 87600h0m0s

  konnectivity:
    agentPort: 8132
    adminPort: 8133

  network:
    provider: kuberouter   # ← critical for bootstrap
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
    clusterDomain: cluster.local

    kubeProxy:
      mode: iptables

    dualStack:
      enabled: false

    nodeLocalLoadBalancing:
      enabled: false
      type: EnvoyProxy
      envoyProxy:
        apiServerBindPort: 7443
        konnectivityServerBindPort: 7132

  extensions:
    helm:
      concurrencyLevel: 5

  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler

  telemetry:
    enabled: false