#!/usr/bin/env bash
set -euo pipefail

# Purpose: Build ephemeral access artifacts for downstream WSL and Windows tooling.
# Preconditions: Controller running, API reachable, and worker token generated by 04-controller-token.sh.
# Invariants: Does not mutate cluster resources; only reads local controller state and writes local artifacts.
# Inputs: CONTROLLER_IP (optional), API_PORT, ARTIFACT_DIR, TOKEN_IN, ADMIN_KUBECONFIG.
# Idempotency: Safe to rerun; artifacts are reconciled/overwritten deterministically.
# Postconditions: kubeconfig and docker endpoint artifacts are available under ./artifacts for external consumers.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/common.sh
source "${SCRIPT_DIR}/scripts/lib/common.sh"
init_script "${BASH_SOURCE[0]}"
register_error_trap

API_PORT="${API_PORT:-6443}"
ARTIFACT_DIR="${ARTIFACT_DIR:-${SCRIPT_DIR}/artifacts}"
TOKEN_IN="${TOKEN_IN:-${ARTIFACT_DIR}/k0s-worker-token}"
ADMIN_KUBECONFIG="${ADMIN_KUBECONFIG:-/var/lib/k0s/pki/admin.conf}"
KUBECONFIG_OUT="${KUBECONFIG_OUT:-${ARTIFACT_DIR}/kubeconfig-controller-ip.yaml}"
DOCKER_HOST_OUT="${DOCKER_HOST_OUT:-${ARTIFACT_DIR}/docker-host-uri}"
CONTROLLER_IP_FILE="${CONTROLLER_IP_FILE:-${ARTIFACT_DIR}/controller-ip}"
WSL_ENV_OUT="${WSL_ENV_OUT:-${ARTIFACT_DIR}/wsl.env}"
WINDOWS_ENV_OUT="${WINDOWS_ENV_OUT:-${ARTIFACT_DIR}/windows.env}"
DOCKER_CONTEXT_NAME="${DOCKER_CONTEXT_NAME:-kubernetes}"
VM_USER="${VM_USER:-${SUDO_USER:-$(id -un)}}"

require_privileged_access

log "Checking API availability"
k0s_kubectl get --raw=/healthz >/dev/null 2>&1 \
  || fail "API server not reachable. Run 02-cluster.sh first."

if [[ ! -f "${TOKEN_IN}" ]]; then
  fail "Worker token artifact not found at ${TOKEN_IN}. Run ./04-controller-token.sh first."
fi

if [[ ! -f "${ADMIN_KUBECONFIG}" ]]; then
  fail "Admin kubeconfig not found at ${ADMIN_KUBECONFIG}. Run ./02-cluster.sh first."
fi

if [[ -z "${CONTROLLER_IP:-}" ]]; then
  CONTROLLER_IP="$(hostname -I | awk '{print $1}')"
fi

[[ -n "${CONTROLLER_IP}" ]] || fail "Unable to determine controller IP. Set CONTROLLER_IP explicitly."

API_SERVER="https://${CONTROLLER_IP}:${API_PORT}"
DOCKER_HOST_URI="ssh://${VM_USER}@${CONTROLLER_IP}"

log "Preparing artifact directory: ${ARTIFACT_DIR}"
mkdir -p "${ARTIFACT_DIR}"

log "Building kubeconfig artifact with controller IP endpoint (${API_SERVER})"
as_root cp "${ADMIN_KUBECONFIG}" "${KUBECONFIG_OUT}"
CLUSTER_NAME="$(as_root k0s kubectl --kubeconfig="${KUBECONFIG_OUT}" config view --output=jsonpath='{.clusters[0].name}')"
[[ -n "${CLUSTER_NAME}" ]] || fail "Could not determine cluster name while patching kubeconfig artifact"
as_root k0s kubectl --kubeconfig="${KUBECONFIG_OUT}" config set-cluster "${CLUSTER_NAME}" --server="${API_SERVER}"
as_root chmod 600 "${KUBECONFIG_OUT}"

log "Writing docker endpoint artifact"
printf '%s\n' "${DOCKER_HOST_URI}" | as_root tee "${DOCKER_HOST_OUT}" >/dev/null
as_root chmod 600 "${DOCKER_HOST_OUT}"

log "Writing controller IP artifact"
printf '%s\n' "${CONTROLLER_IP}" | as_root tee "${CONTROLLER_IP_FILE}" >/dev/null
as_root chmod 600 "${CONTROLLER_IP_FILE}"

log "Writing WSL/Windows environment hint artifacts"
cat <<EOF | as_root tee "${WSL_ENV_OUT}" >/dev/null
CONTROLLER_IP=${CONTROLLER_IP}
API_SERVER=${API_SERVER}
DOCKER_CONTEXT_NAME=${DOCKER_CONTEXT_NAME}
DOCKER_HOST_URI=${DOCKER_HOST_URI}
KUBECONFIG_ARTIFACT=${KUBECONFIG_OUT}
WORKER_TOKEN_ARTIFACT=${TOKEN_IN}
EOF
as_root chmod 600 "${WSL_ENV_OUT}"

cat <<EOF | as_root tee "${WINDOWS_ENV_OUT}" >/dev/null
CONTROLLER_IP=${CONTROLLER_IP}
API_SERVER=${API_SERVER}
DOCKER_CONTEXT_NAME=${DOCKER_CONTEXT_NAME}
DOCKER_HOST_URI=${DOCKER_HOST_URI}
KUBECONFIG_ARTIFACT=${KUBECONFIG_OUT}
WORKER_TOKEN_ARTIFACT=${TOKEN_IN}
EOF
as_root chmod 600 "${WINDOWS_ENV_OUT}"

log "Artifact generation complete"
log " - Kubeconfig: ${KUBECONFIG_OUT}"
log " - Docker host URI: ${DOCKER_HOST_OUT}"
log " - Controller IP: ${CONTROLLER_IP_FILE}"
log " - WSL env hints: ${WSL_ENV_OUT}"
log " - Windows env hints: ${WINDOWS_ENV_OUT}"

summary "Use ../05-configure-wsl/01-configure-docker.sh and ../05-configure-wsl/02-configure-kubectl.sh"

